language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COVERAGE=1

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - phpenv rehash

script:
  - if [[ $COVERAGE == 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $COVERAGE != 1 ]]; then vendor/bin/phpunit; fi

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false