language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - phpenv rehash

script:
  - vendor/bin/phpunit

notifications:
  email: false